### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by flexchar** [umbraco/Umbraco.Headless.Client.NodeJs#15]
When using `client.management.media.create` I get the following error:
`TypeError: Cannot read property 'data' of undefined
    at ApiRequest.<anonymous> (/home/lukas/dev/umbraco_migrate/node_modules/@umbraco/headless-client/dist/ApiRequest.js:124:118)
    at step (/home/lukas/dev/umbraco_migrate/node_modules/@umbraco/headless-client/dist/ApiRequest.js:33:23)
    at Object.throw (/home/lukas/dev/umbraco_migrate/node_modules/@umbraco/headless-client/dist/ApiRequest.js:14:53)
    at rejected (/home/lukas/dev/umbraco_migrate/node_modules/@umbraco/headless-client/dist/ApiRequest.js:6:65)`

It seems that it comes from this snippet in ApiRequest.ts file, line 84
![image](https://user-images.githubusercontent.com/9198896/72258147-9cb7fe00-360d-11ea-86f2-0ecc5442ed9c.png)

I tried to investigate what data is supposed to be. It always declared as any.

Due to lack of docs, it is unclear what is expected to be passed into the function. But inspired by this https://our.umbraco.com/documentation/Umbraco-Heartcore/API-Documentation/Content-Management/media/#create-media 

![image](https://user-images.githubusercontent.com/9198896/72258180-b1949180-360d-11ea-8824-09d8e52a6c7b.png)

I currently create new FormData and try to append content data with a picture. I provide to the function.

EDIT: change to describe the real problem. The original was cause by me by misreading the original error.

**Comment by flexchar** [comment]
I managed to upload it. This issue technically is my own caused problem as I was trying to create stream from remote address.
